# Exported from Render on 2025-07-17T12:17:46Z
services:
- type: web
  name: Test
  runtime: python
  repo: https://github.com/Woohoo-code/Test
  plan: free
  region: virginia
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --host 108.46.220.36 --port $PORT
  autoDeployTrigger: "off"
version: "1"

